export const swapi = 'https://swapi.dev/api'
export const films = '/films'
export const people = '/people'
export const planets = '/planets'
export const species = '/species'
export const starships = '/starships'
export const vehicles = '/vehicles'